# Generated by Django 5.0.4 on 2024-12-27 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hasta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitRequester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Visit Requester',
                'verbose_name_plural': 'Visit Requesters',
            },
        ),
        migrations.CreateModel(
            name='Doktor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hasta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hasta.hasta')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doktor.doktor')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doktor',
                'verbose_name_plural': 'Doktors',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('visit_purpose', models.TextField()),
                ('visit_notes', models.TextField(blank=True, null=True)),
                ('doktor_notes', models.TextField(blank=True, null=True)),
                ('visit_status', models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('completed', 'Completed'), ('draft', 'Draft'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('duration', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('doktor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doktor.doktor')),
                ('hasta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hasta.hasta')),
                ('visit_requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visit_responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_responsible', to='doktor.doktor')),
            ],
        ),
    ]
