# Generated by Django 5.0.4 on 2025-01-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doktor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='doktor',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='hasta',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='visit_requester',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='visit_responsible',
        ),
        migrations.DeleteModel(
            name='VisitRequester',
        ),
        migrations.AlterModelOptions(
            name='doktor',
            options={},
        ),
        migrations.RemoveField(
            model_name='doktor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='doktor',
            name='extra_info',
        ),
        migrations.RemoveField(
            model_name='doktor',
            name='hasta',
        ),
        migrations.RemoveField(
            model_name='doktor',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='doktor',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='doktor',
            name='user',
        ),
        migrations.AddField(
            model_name='doktor',
            name='clinic_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='doktor',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doktor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='doktor',
            name='father',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doktor',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doktor',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doktor',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doktor',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='doktor',
            name='mother',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doktor',
            name='national_id',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='doktor',
            name='place_of_birth',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doktor',
            name='specialization',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='doktor',
            name='work_shift',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doktor',
            name='working_days',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='doktor',
            name='working_hours',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
